// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOJ3jIlg-A7zH6OMypavpqI78j3jt5FeE',
    appId: '1:796128426527:web:88bb58f5fdd21a5866332a',
    messagingSenderId: '796128426527',
    projectId: 'stimuli-59f10',
    authDomain: 'stimuli-59f10.firebaseapp.com',
    storageBucket: 'stimuli-59f10.firebasestorage.app',
    measurementId: 'G-BP8SXJ7KY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrAPkVbMWnrp_mV0BAyQFMZGcZ6ZWRads',
    appId: '1:796128426527:android:a0100469bc5e642a66332a',
    messagingSenderId: '796128426527',
    projectId: 'stimuli-59f10',
    storageBucket: 'stimuli-59f10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLwjJtdKSavaJLIw3NYrTcLmbkl_sdbw',
    appId: '1:796128426527:ios:174ff27c0cfd71c766332a',
    messagingSenderId: '796128426527',
    projectId: 'stimuli-59f10',
    storageBucket: 'stimuli-59f10.firebasestorage.app',
    iosBundleId: 'com.stumili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLwjJtdKSavaJLIw3NYrTcLmbkl_sdbw',
    appId: '1:796128426527:ios:02824d092b3e74d566332a',
    messagingSenderId: '796128426527',
    projectId: 'stimuli-59f10',
    storageBucket: 'stimuli-59f10.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOJ3jIlg-A7zH6OMypavpqI78j3jt5FeE',
    appId: '1:796128426527:web:5c8a94071df4d2d566332a',
    messagingSenderId: '796128426527',
    projectId: 'stimuli-59f10',
    authDomain: 'stimuli-59f10.firebaseapp.com',
    storageBucket: 'stimuli-59f10.firebasestorage.app',
    measurementId: 'G-SC0FH912LJ',
  );
}
